### ISSUE TITLE
Jenkins, consul, github and nubis-builder need to create and export logs

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-meta#24]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#infrastructurelogs

Jenkins, consul, github and nubis-builder need to create and export logs

It's not yet defined how infrastructure logging and log aggregation will work.

Recommendations :

Define a plan in conjunction with opsec for monitoring/response

**Comment by gene1wood** [comment]
Feel free to update the subject to be more clear : We need consul, jenkins (which I believe encompasses nubis-builder) and bastion hosts to generate logs and ship them off the server to somewhere (e.g. s3)

**Comment by gene1wood** [comment]
@gozer Please update the title of this issue to reflect the current list of infrastructure logs that need to be collected
* jenkins logins and actions taken
* bastion hosts logins
* elb access logs
* consul read and write operations on secrets (which I think consul doesn't support)

**Comment by tinnightcap** [comment]
@gene1wood Seriously, just like that you are going to sneak in ELB access logs that are not on the tracking sheet and have never been part of the discussion? This is not in scope of this issue and will need a separate issue filed. We do not, and can not, have fluent collectors running on the ELBs. This is s separate issue and needs to be filed as such. Thanks.

**Comment by gozer** [comment]
A portion of this (syslog stuff) hapenned over in Nubisproject/nubis-base#92

**Comment by gozer** [comment]
- [ ] jenkins logins and actions taken (/var/log/jenkins/jenkins.log)
- [ ] bastion hosts logins (Nubisproject/nubis-base#92)
- [ ] ~~elb access logs~~ (out of scope)
- [ ] ~~consul read and write operations~~ (not available in Consul)

**Comment by gene1wood** [comment]
> Seriously, just like that you are going to sneak in ELB access logs that are not on the tracking sheet and have never been part of the discussion?

Ya, not trying to "sneak" anything. Just wanted to record the outcome from the email thread on infra-aws about the LDAP service. It sounded to me like what Ed wants to do is not do some kind of proxy protocol for the LDAP server to capture source IPs but use ELB access logs instead. Since those are infrastructural (and I would imagine from a nubis perspective not app specific) I thought this would be a good place to record it. (See the thread titled "How to safely create a public LDAP endpoint")

If we should open a distinct ticket for just ELB access logs (or whatever solution you guys would like to use to capture login attempts for LDAP) I'm happy to do so.

Also as far as "sneaking" things in, do remember, I don't have a dog in the fight about what you guys work on, I'm just trying to track your mitigations of risks (through whatever means you deem best). Since we (opsec) are on the hook for identifying which risks IT has accepted vs what has been mitigated and remedied, we need some kind of record of that, which is my only reason for trying to write this stuff down.

**Comment by gene1wood** [comment]
Oh and this isn't fluent collectors on ELBs, it's [enabling access logs in the CloudFormation for the ELB](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-accessloggingpolicy)

**Comment by tinnightcap** [comment]
I do not take any issue with ELB logging. My issue is with constantly shifting requirements. You can cite the email discussion but in truth we have been using ELBs since January, this is not something new. We are consistently "falling behind" and "failing to meet deadlines" due to changing requirements. IMO the time for security to call out new issues to be forced into this release passed more than a month ago. I know this is not on you but is a lack of competent leadership in this project. It is frustrating none-the-less and it often feels like people are so busy covering their asses that they don't give a shit if we ever get anything into production. FWIW, that is exactly your dog in this fight and to say otherwise is misleading at best. No offense intended, just being honest.

**Comment by gozer** [comment]
What could have been done has been done, closing.

**Comment by gdestuynder** [comment]
@gozer can you add details to "what has been done" / what has been done?

**Comment by gozer** [comment]
Syslog fixed on Amazon Linux, so that's /var/log/messages, /var/log/secure, /var/log/maillog
Jenkins: /var/log/jenkins/jenkins.log

**Comment by gdestuynder** [comment]
@gozer do you have a pointer to the code that has the settings for these logs (from which we can discover the S3 bucket), or the S3 bucket itself?

**Comment by RichardWeiss** [comment]
@gdestuynder per our conversation yesterday, we will deliver the log data to a bucket owned by opsec once opsec identifies one for us.

**Comment by gdestuynder** [comment]
@jeffbryner as per previous comment, Nubis team wants to send their logs to a S3 bucket owned by Mozdef that Mozdef would parse.

**Comment by gdestuynder** [comment]
also copying chat from irc with @RichardWeiss:
in the mean time if the logs are stored/accessible elsewhere that would also decrease risk - I'm not sure if thats the case though, my understanding is that a S3 bucket will need to be there in order to store the files anywhere, until then its a log flow that is not saved

**Comment by gdestuynder** [comment]
Just discussed with @RichardWeiss and @gene1wood in the office this morning and it looks like this needs clarifications:

- Storing all logs in a S3 bucket (for ex) on the Nubis side is the most important part so that they're available for forensic purposes.
- Sending security-relevant logs to MozDef is also important and should be done, but is not as critical. Ideally we'd prefer MozDef to be granted read access to your S3 bucket where we pick the logs up (if possible in a standard format)

@gozer or @jd thus, my understanding is that you actually now store these logs in Nubis somewhere, can you point out to where if so?

**Comment by gozer** [comment]
First of all, all fluent forward logs have been archived to S3 since the beginning.

Second, what I was suggesting isn't what you just highlighted. I want to keep Nubis's own log handling its own, and not worry about having to grant others access to look under the covers, so to speak.

Third, my proposal was to just split logs and send *all* of them to an opsec provided bucket, in a format/layout that opsec likes. All logs, not just some logs.

The only interesting point there is that Nubis can change how/where it chooses to archive its logs, without impacting how secops recieves them. Separation of concerns and all.

**Comment by gdestuynder** [comment]
@jeffbryner see gozer's comment (jeff is mozdef's lead - mozdef is our security logging system)

**Comment by jeffbryner** [comment]
"my proposal was to just split logs and send all of them to an opsec provided bucket, in a format/layout that opsec likes. All logs, not just some logs."

This is fine by me as it's similar to what we do today (syslog filters, etc) and allows us some flexibility on the naming convention, format, etc without impacting others. I don't know what those options are (naming/format/etc)? Are you using https://github.com/fluent/fluent-plugin-s3? If so I can give you a first shot at what matters, doesn't matter.

**Comment by gozer** [comment]
Excellent! And yes, it's the plugin we use. Simplest would be sending everything over to your bucket, and you could just specifying destination file name, compression, date slicing, etc.

**Comment by jeffbryner** [comment]
Forgive the fluentd nb question but can we pick a bucket per log type? i.e. OS logs->bucketA, platform (jenkins, etc) logs->bucketB? 

I've no idea what the volume looks like but this might help split the workload for log injestion in that I could use multiple processes, assign them to separate buckets, etc.

**Comment by gozer** [comment]
> Forgive the fluentd nb question but can we pick a bucket per log type? i.e. OS logs->bucketA,
> platform (jenkins, etc) logs->bucketB? 

Yes, we could very easily do that as well, fluentd is pretty good at this kind of stuff. Of course, injecting *all* events in a *single* bucket could be implemented today, quickly, more complex filtering will take some collaboration to get done to your satisfaction.

Either way, I like this approach

**Comment by jeffbryner** [comment]
Do you know what volume of events we are talking about? Rough figures are fine (events/sec, events/day, etc)?

**Comment by gdestuynder** [comment]
@jeffbryner confirms we're getting logs:
jeff | yeah, the normal logs are good (ec2.forward.system.syslog) 

(this does not include ELB logs that we still have to verify separately)
